# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 10m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gofmt
    - govet
    - stylecheck
    - staticcheck
#    - err113
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - gosimple
    - gosec
    - typecheck
    - misspell
    - noctx

linters-settings:
  gofmt:
    simplify: true
  goconst:
    min-len: 3 # minimum length of string constant
    min-occurrences: 6 # minimum number of occurrences

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unused
        - unparam
    - linters:
        - golint
      text: "should be"
    - linters:
        - err113
      text: "do not define dynamic errors"
    - linters:
        - stylecheck
      text: "(should be|should have name of the form)"
