version: "2"
run:
  tests: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - fatcontext
    - gochecksumtype
    - gosmopolitan
    - loggercheck
    - nilnesserr
    - prealloc
    - reassign
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testifylint
    - unconvert
    - wastedassign
    - zerologlint
    - errorlint
    - noctx
    - nilerr
    - unused
    - makezero
    - perfsprint
    - gocritic
  disable:
    - contextcheck
    - err113
    - errchkjson
    - exhaustive
    - gocheckcompilerdirectives
    - gosec
    - musttag
    - protogetter
    - recvcheck
    - unparam
    - wrapcheck
  settings:
    goconst:
      min-len: 3
      min-occurrences: 6
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
          - unparam
          - unused
        path: _test\.go
      - linters:
          - golint
        text: should be
      - linters:
          - err113
        text: do not define dynamic errors
      - linters:
          - staticcheck
        text: (should be|should have name of the form)
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
