# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 10m
  tests: true

linters:
  presets:
    - bugs
    - error
    - unused
    - performance
  disable:
    - gosec # enable it after 1-2 weeks. it failing CI withoutt enough info to fix: https://github.com/erigontech/erigon/actions/runs/5928644129/job/16074701625
    - exhaustive
    - musttag
    - contextcheck
    - wrapcheck
    - err113
    - unparam
    - errchkjson #TODO: enable me
    - makezero #TODO: enable me
    - noctx #TODO: enable me
    - nilerr #TODO: enable me
    - errorlint #TODO: enable me
    - unused #TODO: enable me
    - gocheckcompilerdirectives
    - protogetter
    - recvcheck #TODO: enable me
  enable:
    - unconvert
    #    - predeclared #TODO: enable me
    #    - thelper #TODO: enable me
    - testifylint #TODO: enable me
    - wastedassign
    - gofmt
    - gocritic
    - perfsprint
#    - revive
#    - forcetypeassert
#    - stylecheck

linters-settings:
  gofmt:
    simplify: true
  goconst:
    min-len: 3 # minimum length of string constant
    min-occurrences: 6 # minimum number of occurrences

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unused
        - unparam
    - linters:
        - golint
      text: "should be"
    - linters:
        - err113
      text: "do not define dynamic errors"
    - linters:
        - stylecheck
      text: "(should be|should have name of the form)"
